apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
    name: mongodb-pvc-sc
spec:
    resources:
        requests:
            storage: 100Mi
    accessModes:
        - ReadWriteOnce
    storageClassName: fast
